# Copy this to .settings.yaml and fill it out.

# Screeps account info
screeps_username:
screeps_password:
screeps_ptr: false

# Your Account APK Key
nma_api_key:

# Your Application Name (can be anything)
nma_application: Screeps
